### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shivajid** [akanimax/indian-celeb-gans#1]
Where is the dataset. The data folder is empty

**Comment by akanimax** [comment]
Hello, 
I am not sure if this is still needed, but please refer our [paper](https://ieeexplore.ieee.org/document/9033631/figures#figures) for more details about the dataset. The dataset is granted on a per-request basis and is prohibited to be used for any purposes other than research. Please feel free to send us a formal request of the dataset. 
Regards.
